package Includes;
public class CardPack {
    public static final String[] DEFAULT_WHITE_CARDS = new String[] {
        "RNGesus (Praise Be Unto Him!)",
        "The Van Riper Curse",
        "The Cactus",
        "Blown to Bits: Your Life, Liberty, and Happiness after the Digital Explosion",
        "Randy Valis Dance Palace",
        "Gloria",
        "The Shrekkoning",
        "Shrek, the Green Ogre",
        "Grammar Nazi",
        "Grammar Commie",
        "The Helen Keller Experience",
        "The Top of the Pack",
        "Mr. Littrell's Puzzle of the Day",
        "An Oversized Monkey Wrench",
        "A Turkey Baster",
        "A Blender Model",
        "The Infinite Wisdom of Stack Overflow",
        "Acoustic Fridays",
        "Andy's Rubik's Cube Obsession",
        "Wearing Polos to Mock Interviews",
        "Actually Listening to Mr. Littrell For Once",
        "Expecting Break Cart, But Not Getting It",
        "Catching the Diabetes Virus From Break Cart",
        "Downloading More RAM",
        "Those Times the Juniors Annoy You to No End",
        "BIG BROTHER IS WATCHING YOU, SCOTT",
        "Mr. Starscream",
        "ArgoUML",
        "The Best Programming Language, Eclipse",
        "The Atomic Size of Ms. Savage's Programming Intelligence",
        "while(true)",
        "An Actual Python Actually Biting You And Actually Killing You",
        "Windows > Linux; A scream can be heard in the distance...",
        "Mac OS X > Linux",
        "Orangutang",
        "Ring Around the SYNTAX ERROR",
        "Bunny",
        "Ben's Daily Prayers",
        "The Slight Mention of Ferguson",
        "Five Clicks to Jesus",
        "The Mediocrity of Everyone Who Isn't Ben",
        "Judaism",
        "Community Service Learning Hours",
        "That One Semi-Colon",
        "Crowbar Eckles",
        "My Indentured Servant, Chrome",
        "A Quick Google",
        "RTFM!",
        "DOGE OR RIOT",
        "The Mere Concept of the Juniors",
        "Jerome",
        "Buckey",
        "Chuck",
        "The Wretched iPhone Users",
        "The Holy Bible",
        "The Torah",
        "The Qur'an",
        "</sarcasm>",
        "W3 Validator",
        "Shrek is Love. Shrek is Life",
        "This is a Burn Card",
        "Mrs. Thomas",
        "Making Fun of Other People's Work",
        "Actually Doing Something Productive",
        "Playing Super Crate Box Instead of Work",
        "Deleting Your .minecraft Folder",
        "Deleting System32",
        "Jeremy's Resounding Ability to Keep Focus in Class",
        "Dvorak",
        "Matt's Chat App",
        "Mr. Valis Chastising the Class",
        "Jython",
        "Programming with Coffee, Predators, or Music Notes",
        "Jousting, the Official Sport of Maryland",
        ">.<",
        "Pointers",
        "The Disappointment of Finding Out Hashing Has Nothing to Do With Hash Browns",
        "Getting Around the School Filter",
        "The Death of Shrek on VHS",
        "Galax Krig, Game of the Year 2015",
        "Mr. Littrell's Red Plaid Shirt",
        "An Interpretive Dance About Math",
        "The School Nurse",
        "Math, Not Even Once",
        "Something",
        "Nothing",
        "The Rivalry With the Juniors",
        "The \"Rivalry\" With CISCO",
        "Those Taunts From Break Cart",
        "Snoopchat",
        "@randyvalis",
        "Missing Grant",
        "The Pronunciation of Char",
        "Having Inappropriate Sleeves for a Sweater",
        "When In Doubt, Stack Overflow",
        "http://www.downloadmoreram.com/",
        "Lord Gaben",
        "A Real Blender",
        "Daeson Wow",
        "#JohnFellDown"
    };
    public static final String[] DEFAULT_BLACK_CARDS = new String[] {
        "	Mr. Littrell may not let us watch Shrek, but he does let us ____.",
        "	Everyone was surprised when Ben exclaimed his approval of ____.",
        "	What ruined the Secret Santa?",
        "	Camen is recording today, what should he record?",
        "	Only ____ will bring back Grant.",
        "		Mr. Valis was irate to learn that ____ spent their time doing ____.",
        "	____ is love. ____ is life.",
        "	Obama quivered at Putin's plan to ____.",
        "	What is Break Cart serving?",
        "	Caitlyn Jollie may not be jolly, but she sure is ____.",
        "	What is Ben's favorite Biblical story?",
        "	Why are you getting extra homework this week?",
        "	The class laughed when Mr. Littrell decided to rename his Number class to ____.",
        "			3 Card Story, Let's Go!",
        "			____ + ____ = ____",
        "	r/ ____.",
        "		____.com/____",
        "	What is your Blown to Bits essay about",
        "	I'd be a powerful wizard if only I could channel ____.",
        "		____: ____ Edition.",
        "	Explain Like I'm Five: ____.",
        "	Linux's downfall started with the ____ update.",
        "	What should be Mr. Littrell's next intrepretive dance?",
        "	____, the deadly killer.",
        "	What should be avoided at all costs?",
        "	What did Mr. Littrell announce today?",
        "	I'd switch to iPhone, if only they added ____.",
        "	Now that the bug is patched, I now have a ____ problem.",
        "		A new security breach has left ____ vulnerable to ____.",
        "	What is black and white and red all over?",
        "	Who wins the console wars?",
        "	Can you believe it? The Juniors did ____ AGAIN!",
        "		____ on ____ Action",
        "	Who just walked in the room?",
        "	Nah man. ____ is wayyyy better than Halo."  
    };
    
}
